/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KuglrBzWoft
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Button } from '@/components/ui/button';
import Image from 'next/image';
import logo from '@/public/images/logo-light.svg';
import youtube from '@/public/images/icon-youtube.svg';
import pinInterest from '@/public/images/icon-pinterest.svg';
import instargram from '@/public/images/icon-instagram.svg';
import facebook from '@/public/images/icon-facebook.svg';
import twitter from '@/public/images/icon-twitter.svg';

const links = [youtube, twitter, facebook, pinInterest, instargram];
export function Footer() {
	return (
		<footer className="mt-auto bg-[#2d314d] text-white py-8 px-4 md:px-10 lg:px-16">
			<div className="container mx-auto flex flex-col md:flex-row justify-between items-center space-y-6 md:space-y-0">
				<div className="flex flex-col items-center md:items-start space-y-4">
					<div className="flex items-center space-x-2">
						<Image src={logo} alt="logo" width={150} height={22} />
					</div>
					<div className="flex space-x-4">
						{links.map((link) => (
							<Image key={link} src={link} alt="logo" />
						))}
					</div>
				</div>
				<div className="flex flex-col md:flex-row md:space-x-16 space-y-4 md:space-y-0 text-center md:text-left">
					<div className="space-y-2">
						<a href="#" className="block hover:text-gray-200 text-sm">
							About Us
						</a>
						<a href="#" className="block hover:text-gray-200 text-sm">
							Contact
						</a>
						<a href="#" className="block hover:text-gray-200 text-sm">
							Blog
						</a>
					</div>
					<div className="space-y-2">
						<a href="#" className="block hover:text-gray-200 text-sm">
							Careers
						</a>
						<a href="#" className="block hover:text-primary">
							Support
						</a>
						<a href="#" className="block hover:text-gray-200 text-sm">
							Privacy Policy
						</a>
					</div>
				</div>
				<div className="flex flex-col items-center md:items-end space-y-4">
					<Button className="bg-gradient-to-r from-[#33d35e] to-[#2ab6d9] text-white px-6 py-2 rounded-full">
						Request Invite
					</Button>
					<p className="text-sm text-muted-foreground">
						© Easybank. All Rights Reserved
					</p>
				</div>
			</div>
		</footer>
	);
}

function BanknoteIcon(props: any) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<rect width="20" height="12" x="2" y="6" rx="2" />
			<circle cx="12" cy="12" r="2" />
			<path d="M6 12h.01M18 12h.01" />
		</svg>
	);
}

function FacebookIcon(props: any) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
		</svg>
	);
}

function InstagramIcon(props: any) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
			<path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
			<line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
		</svg>
	);
}

function PinIcon(props: any) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<line x1="12" x2="12" y1="17" y2="22" />
			<path d="M5 17h14v-1.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V6h1a2 2 0 0 0 0-4H8a2 2 0 0 0 0 4h1v4.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24Z" />
		</svg>
	);
}

function TwitterIcon(props: any) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
		</svg>
	);
}

function XIcon(props: any) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M18 6 6 18" />
			<path d="m6 6 12 12" />
		</svg>
	);
}

function YoutubeIcon(props: any) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17" />
			<path d="m10 15 5-3-5-3z" />
		</svg>
	);
}
