/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xhnqhDUULK3
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from 'next/link';
import { Sheet, SheetTrigger, SheetContent } from '@/components/ui/sheet';
import { Button } from '@/components/ui/button';
import logo from '@/public/images/logo.svg';
import Image from 'next/image';

export function Navigation() {
	return (
		<header className="fixed top-0 left-0 z-50 w-full bg-white shadow-md">
			<div className=" mx-auto flex h-16 items-center justify-between px-4 md:px-10">
				<Link href="#" className="flex items-center" prefetch={false}>
					<Image src={logo} alt="logo image" height={22} width={150} />
				</Link>
				<nav className="hidden md:flex items-center space-x-6">
					<Link
						href="#"
						className="text-sm font-medium hover:text-primary transition-colors"
						prefetch={false}
					>
						About
					</Link>
					<Link
						href="#"
						className="text-sm font-medium hover:text-primary transition-colors"
						prefetch={false}
					>
						Contact
					</Link>
					<Link
						href="#"
						className="text-sm font-medium hover:text-primary transition-colors"
						prefetch={false}
					>
						Blog
					</Link>
					<Link
						href="#"
						className="text-sm font-medium hover:text-primary transition-colors"
						prefetch={false}
					>
						Careers
					</Link>
				</nav>
				<Link
					href="#"
					className="hidden rounded-full md:inline-flex h-9 items-center justify-center    bg-gradient-to-r from-l-green to-b-cyan px-6 text-sm font-medium text-white shadow-md transition-colors hover:from-l-green/80 hover:to-b-cyan/80 focus:outline-none focus:ring-2 focus:ring-l-green/20 focus:ring-offset-2"
					prefetch={false}
				>
					Sign Up
				</Link>
				<Sheet>
					<SheetTrigger asChild>
						<Button variant="outline" size="icon" className="md:hidden">
							<MenuIcon className="h-6 w-6" />
							<span className="sr-only">Toggle navigation menu</span>
						</Button>
					</SheetTrigger>
					<SheetContent side="left" className="md:hidden">
						<div className="flex flex-col items-start space-y-4 p-4">
							<Link
								href="#"
								className="text-sm font-medium hover:text-primary transition-colors"
								prefetch={false}
							>
								About
							</Link>
							<Link
								href="#"
								className="text-sm font-medium hover:text-primary transition-colors"
								prefetch={false}
							>
								Contact
							</Link>
							<Link
								href="#"
								className="text-sm font-medium hover:text-primary transition-colors"
								prefetch={false}
							>
								Blog
							</Link>
							<Link
								href="#"
								className="text-sm font-medium hover:text-primary transition-colors"
								prefetch={false}
							>
								Careers
							</Link>
							<Link
								href="#"
								className="hidden md:inline-flex h-9 items-center justify-center rounded-full bg-gradient-to-r from-l-green to-b-cyan px-6 text-sm font-medium text-white shadow-md transition-colors hover:from-l-green/80 hover:to-b-cyan/80 focus:outline-none focus:ring-2 focus:ring-l-green/20 focus:ring-offset-2"
								prefetch={false}
							>
								Sign Up
							</Link>
						</div>
					</SheetContent>
				</Sheet>
			</div>
		</header>
	);
}

function MenuIcon(props: any) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<line x1="4" x2="20" y1="12" y2="12" />
			<line x1="4" x2="20" y1="6" y2="6" />
			<line x1="4" x2="20" y1="18" y2="18" />
		</svg>
	);
}

function XIcon(props: any) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M18 6 6 18" />
			<path d="m6 6 12 12" />
		</svg>
	);
}
